name: Release

on:
  push:
    branches:
      - master
      - release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
          
      - name: Merge master to develop
        run: |
            git fetch --unshallow
            git checkout develop
            git pull
            git merge --no-ff master -m "chore(merge): Merge branch 'master' into 'develop'"
            git push